// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Data;

namespace Recipes.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20211127122953_SeedMoreDataAgain")]
    partial class SeedMoreDataAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Recipes.Data.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepper"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Baking Soda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hot Sauce"
                        });
                });

            modelBuilder.Entity("Recipes.Data.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instruction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Add cup of Salt",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add cup of pepper",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mix warm milk, yeast, 2 tsp sugar and let is sit for 10-15 mins until foamy",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mix flour, salt, and yeast in a bowl or mixer",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Add Sugar, butter, and egg",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Mix until all ingredients are incorporated and form a smooth dough.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Transfer to a light greased bowl and let it rise for 1 hour or until the size is doubled.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Divide dough into 24 equal parts and shape it into a ball.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dip dough into the breadcrumbs and arrange in a pan.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Let it rise for another 20 mins.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Pre-heat oven to 350°F",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bake for 20-25 mins or until golden brown.",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Cut the fish into 1×3 inch slices.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "In a small bowl, beat the egg for coating.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "In a separate bowl, mix flour, salt, black pepper, and paprika.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Coat the fish in the following order: Egg, flour mix, egg again and panko then then flour.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Heat the oil in a deep skillet over medium-high heat. Add the coated fish but don’t crowd the pan. Cook for 2 minutes or until the bottoms are golden brown. Carefully flip the pieces over with tongs, and cook another 2 minutes or until the other side is golden brown.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Drain on paper towels.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Top it off with Kewpie mayo, Okonomi Sauce and Bonito flakes.",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Serve and Enjoy!",
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("Recipes.Data.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Best Recipe",
                            Title = "Recipe 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Not Quite The Best Recipe",
                            Title = "Recipe 2"
                        });
                });

            modelBuilder.Entity("Recipes.Data.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 1,
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("Recipes.Data.Instruction", b =>
                {
                    b.HasOne("Recipes.Data.Recipe", null)
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Data.RecipeIngredient", b =>
                {
                    b.HasOne("Recipes.Data.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Data.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
